# LIST

In [20]:
l1=['a',1,'m',3,'o',0,'p','$','#',10,'x']
print("length of string:",len(l1))
print("index of element $ in list:",l1.index('$'))
l1.append('!')
l1.insert(5,7)
l2=[10,11,12]
l1.extend(l2)
print("new l1 list : ",l1)
l3=l1.copy()+l2.copy()
print("l3:",l3)
20 in l1
l2.clear()
print('l2',l2)
print("l1 count",l1.count(20))
l3.remove(10)
print("l3",l3)

list1=['a','m','s','x','y','z']
list1.remove('a')
print(list1)

length of string: 11
index of element $ in list: 7
new l1 list :  ['a', 1, 'm', 3, 'o', 7, 0, 'p', '$', '#', 10, 'x', '!', 10, 11, 12]
l3: ['a', 1, 'm', 3, 'o', 7, 0, 'p', '$', '#', 10, 'x', '!', 10, 11, 12, 10, 11, 12]
l2 []
l1 count 0
l3 ['a', 1, 'm', 3, 'o', 7, 0, 'p', '$', '#', 'x', '!', 10, 11, 12, 10, 11, 12]
['m', 's', 'x', 'y', 'z']


# ARRAY(NUMPY)

In [6]:
#import numpy
import numpy as np
#check numpy version
print(np.__version__)
#1D array declare
arr = np.array([1, 2, 3, 4, 5])
print(arr)
#check type
print(type(arr))
#2D array declare
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d) 
#3d array declare
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3d) 
#check dimention of all the mentioned array
print("dimention of array \n 1. arr : {} \n 2. arr2d : {} \n 3. arr3d : {} ".format(arr.ndim,arr2d.ndim,arr3d.ndim))

#creation of 5 dimention array
arr5d = np.array([1, 2, 3, 4], ndmin=5)

print(arr5d)
print('number of dimensions :', arr5d.ndim) 
#array[dimension,element]
print("print 2 dimension array 2nd dim  3rd element: ", arr2d[1,2])

1.14.3
[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dimention of array 
 1. arr : 1 
 2. arr2d : 2 
 3. arr3d : 3 
[[[[[1 2 3 4]]]]]
number of dimensions : 5
print 2 dimension array 2nd dim  3rd element:  6


# STRING

In [11]:
s1="This iS strIng opERation test"
u=s1.upper()
l=s1.lower()
c=s1.capitalize()
cen=s1.center(40)
print("all upper: ",u,"\n all lower : ",l,"\n capitalize : ",c,"\n center: ",cen)
enc=s1.encode()
print("encode verson of the string : ",enc)

all upper:  THIS IS STRING OPERATION TEST 
 all lower :  this is string operation test 
 capitalize :  This is string operation test 
 center:       This iS strIng opERation test      
encode verson of the string :  b'This iS strIng opERation test'


# DICTIONARY