# LIST

In [20]:
l1=['a',1,'m',3,'o',0,'p','$','#',10,'x']
print("length of string:",len(l1))
print("index of element $ in list:",l1.index('$'))
l1.append('!')
l1.insert(5,7)
l2=[10,11,12]
l1.extend(l2)
print("new l1 list : ",l1)
l3=l1.copy()+l2.copy()
print("l3:",l3)
20 in l1
l2.clear()
print('l2',l2)
print("l1 count",l1.count(20))
l3.remove(10)
print("l3",l3)

list1=['a','m','s','x','y','z']
list1.remove('a')
print(list1)

length of string: 11
index of element $ in list: 7
new l1 list :  ['a', 1, 'm', 3, 'o', 7, 0, 'p', '$', '#', 10, 'x', '!', 10, 11, 12]
l3: ['a', 1, 'm', 3, 'o', 7, 0, 'p', '$', '#', 10, 'x', '!', 10, 11, 12, 10, 11, 12]
l2 []
l1 count 0
l3 ['a', 1, 'm', 3, 'o', 7, 0, 'p', '$', '#', 'x', '!', 10, 11, 12, 10, 11, 12]
['m', 's', 'x', 'y', 'z']


# ARRAY(NUMPY)

In [6]:
#import numpy
import numpy as np
#check numpy version
print(np.__version__)
#1D array declare
arr = np.array([1, 2, 3, 4, 5])
print(arr)
#check type
print(type(arr))
#2D array declare
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d) 
#3d array declare
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3d) 
#check dimention of all the mentioned array
print("dimention of array \n 1. arr : {} \n 2. arr2d : {} \n 3. arr3d : {} ".format(arr.ndim,arr2d.ndim,arr3d.ndim))

#creation of 5 dimention array
arr5d = np.array([1, 2, 3, 4], ndmin=5)

print(arr5d)
print('number of dimensions :', arr5d.ndim) 
#array[dimension,element]
print("print 2 dimension array 2nd dim  3rd element: ", arr2d[1,2])

1.14.3
[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dimention of array 
 1. arr : 1 
 2. arr2d : 2 
 3. arr3d : 3 
[[[[[1 2 3 4]]]]]
number of dimensions : 5
print 2 dimension array 2nd dim  3rd element:  6


# STRING

In [11]:
s1="This iS strIng opERation test"
u=s1.upper()
l=s1.lower()
c=s1.capitalize()
cen=s1.center(40)
print("all upper: ",u,"\n all lower : ",l,"\n capitalize : ",c,"\n center: ",cen)
enc=s1.encode()
print("encode verson of the string : ",enc)

all upper:  THIS IS STRING OPERATION TEST 
 all lower :  this is string operation test 
 capitalize :  This is string operation test 
 center:       This iS strIng opERation test      
encode verson of the string :  b'This iS strIng opERation test'


# DICTIONARY

In [29]:

d1={'manu':'ferguson','bayern':'kahn','real_madrid':'raul','barca':'messi','juventus':'ronaldo'}
#clear()
d2=d1.copy()
print("d2: ",d2)
k=('k1','k2','k3')
v=('v1')
fk=dict.fromkeys(k,v)
print("print fromkey: ",fk)
print("get value of manu: ",d1.get('manu'))

print("get all items of d1: ",d1.items())
print("get all keys of d1: ",d1.keys())
d1.pop('barca') #mention the key , to which you want to remove
print("dictionary after removing barca: ",d1)
d1.popitem() # last inserted item will be removed
print("after popitem used , d1 is : ",d1)
#d1.setdefault("milan":"maldini")
print(d1)
d1.update({'liverpool':'gerard'})
print("print d1 after new entry liverpool is updated : ",d1)
print("print all d1 values: ",d1.values())


d2:  {'manu': 'ferguson', 'bayern': 'kahn', 'real_madrid': 'raul', 'barca': 'messi', 'juventus': 'ronaldo'}
print fromkey:  {'k1': 'v1', 'k2': 'v1', 'k3': 'v1'}
get value of manu:  ferguson
get all items of d1:  dict_items([('manu', 'ferguson'), ('bayern', 'kahn'), ('real_madrid', 'raul'), ('barca', 'messi'), ('juventus', 'ronaldo')])
get all keys of d1:  dict_keys(['manu', 'bayern', 'real_madrid', 'barca', 'juventus'])
dictionary after removing barca:  {'manu': 'ferguson', 'bayern': 'kahn', 'real_madrid': 'raul', 'juventus': 'ronaldo'}
after popitem used , d1 is :  {'manu': 'ferguson', 'bayern': 'kahn', 'real_madrid': 'raul'}
{'manu': 'ferguson', 'bayern': 'kahn', 'real_madrid': 'raul'}
print d1 after new entry liverpool is updated :  {'manu': 'ferguson', 'bayern': 'kahn', 'real_madrid': 'raul', 'liverpool': 'gerard'}
print all d1 values:  dict_values(['ferguson', 'kahn', 'raul', 'gerard'])


In [39]:
dict1={
    'a':'apple',
    'b':'banana',
    'c':'cheery',
    'd':'dragon_fruit',
}
vowel={'a','e','i','o','u'}

for k,v in dict1.items():
    if k in vowel:
        print(" value of {0} is {1}.".format(k,dict1[k]))

 value of a is apple.


In [48]:
s1='mississippiooaaii'
vowel={'a','e','i','o','u'}
dv={}
dc={}
for i in s1:
    if i in vowel:
        dv[i]=dv.get(i,0)+1
        print("after check {} dictionary is {}".format(i,dv))
    else:
        dc[i]=dc.get(i,0)+1
        print("after check {} dictionary is {}".format(i,dc))
for k,v in dv.items():
    print("for vowel letters {} occured {} times ".format(k,v))
for k,v in dc.items():
    print("for consonand letters {} occured {} times ".format(k,v))
        

after check m dictionary is {'m': 1}
after check i dictionary is {'i': 1}
after check s dictionary is {'m': 1, 's': 1}
after check s dictionary is {'m': 1, 's': 2}
after check i dictionary is {'i': 2}
after check s dictionary is {'m': 1, 's': 3}
after check s dictionary is {'m': 1, 's': 4}
after check i dictionary is {'i': 3}
after check p dictionary is {'m': 1, 's': 4, 'p': 1}
after check p dictionary is {'m': 1, 's': 4, 'p': 2}
after check i dictionary is {'i': 4}
after check o dictionary is {'i': 4, 'o': 1}
after check o dictionary is {'i': 4, 'o': 2}
after check a dictionary is {'i': 4, 'o': 2, 'a': 1}
after check a dictionary is {'i': 4, 'o': 2, 'a': 2}
after check i dictionary is {'i': 5, 'o': 2, 'a': 2}
after check i dictionary is {'i': 6, 'o': 2, 'a': 2}
for vowel letters i occured 6 times 
for vowel letters o occured 2 times 
for vowel letters a occured 2 times 
for consonand letters m occured 1 times 
for consonand letters s occured 4 times 
for consonand letters p occured 2 

In [42]:
   import string
    def LetterCount(str):
            str= str.lower().strip()
            str = str.strip(string.punctuation)
            list1=list(str)
            lcDict= {}
            for l in list1:
                    if l.isalpha():
                            if l in lcDict:
                                    lcDict[l] +=1
                            else:
                                    lcDict[l]= 1
            print lcDict

    LetterCount("Abracadabra, Monsignor")

IndentationError: unexpected indent (<ipython-input-42-dc24f08471dd>, line 2)